### ISSUE TITLE
Fix app naming convention for Splunk ES.

### ISSUE THREAD

**Issue by jgarman** [carbonblack/splunk-arf-app#6]
Since the app does not follow the normal naming convention, you will need to put in your instructions that for all Enterprise Security users they need to update the stanza “[app_imports_update://update_es]” in the file below to allow the ES app to trust this app and its extractions.
a.       $SPLUNK_HOME/etc/apps/SplunkEnterpriseSecuritySuite/local/inputs.conf
b.      See section “The Update ES modular input” - http://docs.splunk.com/Documentation/ES/4.1.0/Install/InstallTechnologyAdd-ons

**Comment by askthedragon** [comment]
This is for Splunk Enterprise Security (ES).  Kyle suggests having 2 versions of the app.  One for ES without dashboards, one with dashboards (non-ES).  Need to change id field and directory name to include "DA-".  Or add '|(carbon*)' in SplunkEnterpriseSEcuritySuite/local/inputs.conf for ES search head.  Also include these instructions in the documentation page on splunkbase.

DA = Domain Addon ( use this most likely to avoid confusion for customers )
TA = Technology Addon ( already have a TA for CbER )
SA = Supporting Addon

http://docs.splunk.com/Documentation/ES/latest/Install/InstallTechnologyAdd-ons#Import_add-ons_with_a_different_naming_convention.

DA-carbonblack-enterprise-response-version.spl

**Comment by askthedragon** [comment]
Because of our naming convention, it is required to modify `inputs.conf` located in `SplunkEnterpriseSEcuritySuite/local/inputs.conf` and add `|(carbon*)` to the `[app_imports_update://update_es]` stanza.

**Comment by jgarman** [comment]
fixed in new app
