### ISSUE TITLE
Fix compatibility with distributed Splunk environment

### ISSUE THREAD

**Issue by jgarman** [carbonblack/splunk-arf-app#7]
With the current configuration of the app, it does not work in a distributed environment unless you deploy this app to the indexers.  Unless you can figure out a work around, your docs should probably be updated to state that. 
a.       The ideal scenario would be to limit the commands to only run on the search heads and not the indexers.

**Comment by askthedragon** [comment]
Add documentation to install the app on search heads and indexers.
SPLUNK_HOME/etc/system/local/distsearch.conf
[replicationBlacklist]
carbonblack = apps/carbonblack-enterprise-response/...

and

local = true in commands.conf

**Comment by askthedragon** [comment]
Added documentation on how to fix replication issue
